### ISSUE TITLE
implicit declaration of function 'esp_a2d_register_data_callback'

### ISSUE THREAD

**Issue by kryvosheiaivan** [MhageGH/esp32_BT_Speaker#1]
Hello!
I am going to try your project but i faced with this error:

implicit declaration of function 'esp_a2d_register_data_callback'  
Function is located in main.c.
Could  you help me?

**Comment by MhageGH** [comment]
Sorry  I don't know. 
'esp_a2d_register_data_callback' is Bluetooth A2DP API provided by esp-idf.
http://esp-idf.readthedocs.io/en/latest/api-reference/bluetooth/esp_a2dp.html

**Comment by kryvosheiaivan** [comment]
If you open that website, you will see that developers remove that function(( 
Did you do that program by yourself?
